// chatbot/vue-ts/src/components/Chatbot/Inspector/Message-inspector/Message-inspector.vue
<template>
    <div>
        <h1>Component</h1>

        <label>Label
            <input placeholder="Enter label"
                   v-batch
                   v-model="label"
                   @input="changeCellProp(props.label, label)">
        </label>

        <label>Description
            <input type="text"
                   placeholder="Enter description"
                   v-batch
                   v-model="description"
                   @input="changeCellProp(props.description, description)">
        </label>

        <label>Icon (Base64)
            <span class="icon-input-logo"></span>
            <input type="text"
                   class="icon-input"
                   placeholder="Enter icon"
                   spellcheck="false"
                   v-batch
                   v-model="icon"
                   @input="changeCellProp(props.icon, icon)">
        </label>

        <div class="ports">
            <div class="out-ports-bar">
                <span>Out Ports</span>
                <button :disabled="!canAddPort"
                        @click="addCellPort()"
                        class="add-port"
                        data-tooltip="Add Output Port">
                </button>
            </div>
            <div class="port" v-for="port in ports" :key="port.id">
                <input placeholder="Label"
                       v-batch
                       v-model="port.label"
                       @input="changeCellPort(port)"/>
                <div class="remove-port"
                     @click="removeCellPort(port.id)"
                     data-tooltip="Remove Output Port"></div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import Component from 'vue-class-component';
    import { Prop } from 'vue-property-decorator';
    import type { app } from '../../../../joint-plus/shapes';

    import { BaseInspector } from '../Base-inspector/base-inspector';
    interface InspectorPort {
        id: string;
        label: string;
    }
    @Component({})
    export default class MessageInspector extends BaseInspector {
        @Prop() cell: app.Message;
        public label = '';
        public description = '';
        public icon = '';
        public ports = [] as InspectorPort[];
        public canAddPort = false;
        public props = {
            label: ['attrs', 'label', 'text'],
            description: ['attrs', 'description', 'text'],
            icon: ['attrs', 'icon', 'xlinkHref'],
            portLabel: ['attrs', 'portLabel', 'text']
        }
        public addCellPort(): void {
            this.cell.addDefaultPort();
            this.assignFormPorts();
        }
        public removeCellPort(portId: string): void {
            this.cell.removePort(portId);
            this.assignFormPorts();
        }
        public changeCellPort(port: InspectorPort): void {
            const { cell, props } = this;
            cell.portProp(port.id, props.portLabel, port.label);
        }
        protected assignFormFields(): void {
            const { cell, props } = this;
            this.label = cell.prop(props.label);
            this.description = cell.prop(props.description);
            this.icon = cell.prop(props.icon);
            this.assignFormPorts();
        }
        private assignFormPorts(): void {
            const { cell, props } = this;
            this.canAddPort = cell.canAddPort('out');
            this.ports = cell.getGroupPorts('out').map(({ id }) => {
                return {
                    id,
                    label: cell.portProp(id, props.portLabel)
                }
            });
        }
    }
</script>

// chatbot/react-redux-ts/src/components/Chatbot/Inspector/MessageInspector.tsx
import React, { useCallback, useState } from 'react';
import { useBaseInspector } from './useBaseInspector';
import Input from '../Input/Input';

import type { ChangeEvent, ReactElement } from 'react';
import type { app } from '../../../joint-plus/shapes';

interface Props {
    cell: app.Message;
}

interface InspectorPort {
    id: string;
    label: string;
}

const cellProps = {
    label: ['attrs', 'label', 'text'],
    description: ['attrs', 'description', 'text'],
    icon: ['attrs', 'icon', 'xlinkHref'],
    portLabel: ['attrs', 'portLabel', 'text']
};

const MessageInspector = (props: Props): ReactElement => {

    const { cell } = props;

    const [label, setLabel] = useState<string>('');
    const [description, setDescription] = useState<string>('');
    const [icon, setIcon] = useState<string>('');
    const [ports, setPorts] = useState<InspectorPort[]>([]);
    const [canAddPort, setCanAddPort] = useState<boolean>(false);

    const assignFormPorts = useCallback((): void => {
        setCanAddPort(cell.canAddPort('out'));
        setPorts(cell.getGroupPorts('out').map(({ id }) => {
            return {
                id,
                label: cell.portProp(id, cellProps.portLabel)
            };
        }));
    }, [cell]);

    const assignFormFields = useCallback((): void => {
        setLabel(cell.prop(cellProps.label));
        setDescription(cell.prop(cellProps.description));
        setIcon(cell.prop(cellProps.icon));
        assignFormPorts();
    }, [cell, assignFormPorts]);

    const changeCellProp = useBaseInspector({ cell, assignFormFields });

    const addCellPort = (): void => {
        cell.addDefaultPort();
        assignFormPorts();
    };

    const removeCellPort = (portId: string): void => {
        cell.removePort(portId);
        assignFormPorts();
    };

    const changeCellPort = (port: InspectorPort, value: string): void => {
        cell.portProp(port.id, cellProps.portLabel, value);
    };

    return (
        <>
            <h1>Component</h1>

            <label>Label
                <Input type="text"
                    placeholder="Enter label"
                    value={label}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.label, e.target.value)}
                />
            </label>

            <label>Description
                <Input type="text"
                    placeholder="Enter description"
                    value={description}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.description, e.target.value)}
                />
            </label>

            <label>Icon (Base64)
                <span className="icon-input-logo"/>
                <Input className="icon-input"
                    type="text"
                    placeholder="Enter icon"
                    value={icon}
                    spellCheck={false}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.icon, e.target.value)}
                />
            </label>

            <div className="ports">
                <div className="out-ports-bar">
                    <span>Out Ports</span>
                    <button disabled={!canAddPort}
                        onClick={addCellPort}
                        className="add-port"
                        data-tooltip="Add Output Port">
                    </button>
                </div>
                {ports.map(port => {
                    return (
                        <div key={port.id} className="port">
                            <Input defaultValue={port.label}
                                onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellPort(port, e.target.value)}
                            />
                            <button className="remove-port"
                                onClick={() => removeCellPort(port.id)}
                                data-tooltip="Remove Output Port">
                            </button>
                        </div>
                    );
                })}
            </div>
        </>
    );
};

export default MessageInspector;
